const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const crypto = require('node:crypto');
const { createDatabase } = require('./database');
const { backupName, createBackupFile } = require('./backup-service');
const { restoreBackup } = require('./restore-service');
const { cleanContent, decoded, escapedContent } = require('./lib/content');
const { cookies, createLoginLimiter, hashPassword, validPassword } = require('./lib/auth');
const { migrate } = require('./lib/schema');
const { mediaDiagnostics, validMediaSignature } = require('./lib/media');
const { receiveFile } = require('./lib/http');
const { bibleSearchExpression } = require('./lib/bible');

const ROOT = __dirname;
for (const line of fs.existsSync(path.join(ROOT, '.env')) ? fs.readFileSync(path.join(ROOT, '.env'), 'utf8').split(/\r?\n/) : []) { const [key, ...value] = line.split('='); if (key && !process.env[key]) process.env[key] = value.join('='); }
const PORT = Number(process.env.PORT || 8080);
const DATA_DIR = process.env.DATA_DIR ? path.resolve(process.env.DATA_DIR) : path.join(ROOT, 'data');
const DB_FILE = path.join(DATA_DIR, 'biblio.db');
const BIBLE_DB_FILE = process.env.BIBLE_DB_FILE ? path.resolve(process.env.BIBLE_DB_FILE) : path.join(ROOT, 'resources', 'bible', 'bible.sqlite');
const RESTORE_FILE = path.join(DATA_DIR, '.biblio-restore-pending.zip');
if (fs.existsSync(RESTORE_FILE)) {
  restoreBackup(fs.readFileSync(RESTORE_FILE), DATA_DIR);
  fs.rmSync(RESTORE_FILE, { force: true });
}
const MEDIA_DIR = path.join(DATA_DIR, 'media');
fs.mkdirSync(MEDIA_DIR, { recursive: true });
const pool = createDatabase(DB_FILE);
const query = (text, values = []) => pool.query(text, values);
if (!fs.existsSync(BIBLE_DB_FILE)) throw new Error('Módulo SQLite offline da Bíblia não encontrado.');
const biblePool = createDatabase(BIBLE_DB_FILE, { readonly: true });
const bibleQuery = (text, values = []) => biblePool.query(text, values);
const textValue = (value, max = 1000000) => String(value || '').trim().slice(0, max);
const list = value => [...new Set(String(value || '').split(',').map(v => v.trim()).filter(Boolean))];
const loginLimiter = createLoginLimiter();

async function init() {
  await migrate(query);
}
async function userFor(req) { const id = cookies(req).biblio_session; if (!id) return null; await query('DELETE FROM sessions WHERE expires_at < now()'); return (await query('SELECT u.id,u.username FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.id=$1 AND s.expires_at>now()', [id])).rows[0] || null; }
async function createSession(res, userId) { const id = crypto.randomBytes(32).toString('hex'); await query(`INSERT INTO sessions(id,user_id,expires_at) VALUES($1,$2,now()+interval '30 days')`, [id, userId]); res.setHeader('set-cookie', `biblio_session=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=2592000${process.env.PUBLIC_HTTPS === 'true' ? '; Secure' : ''}`); }
async function details(id) {
  const article = (await query('SELECT a.*,t.name theme_name,t.parent_id theme_parent_id,p.name theme_parent_name FROM articles a LEFT JOIN themes t ON t.id=a.theme_id LEFT JOIN themes p ON p.id=t.parent_id WHERE a.id=$1', [id])).rows[0]; if (!article) return null;
  article.content = article.content_format === 'html' ? cleanContent(article.content) : escapedContent(article.content);
  const [authors,tags,sources,attachments] = await Promise.all([
    query('SELECT a.id,a.name FROM authors a JOIN article_authors x ON x.author_id=a.id WHERE x.article_id=$1 ORDER BY a.name',[id]),
    query('SELECT t.id,t.name FROM tags t JOIN article_tags x ON x.tag_id=t.id WHERE x.article_id=$1 ORDER BY t.name',[id]),
    query('SELECT s.* FROM sources s JOIN article_sources x ON x.source_id=s.id WHERE x.article_id=$1 ORDER BY s.title',[id]),
    query('SELECT * FROM attachments WHERE article_id=$1 ORDER BY id DESC',[id])
  ]); article.theme = article.theme_id ? { id: article.theme_id, name: article.theme_name, parent: article.theme_parent_id ? { id: article.theme_parent_id, name: article.theme_parent_name } : null } : null; delete article.theme_name; delete article.theme_parent_id; delete article.theme_parent_name; article.authors=authors.rows; article.tags=tags.rows; article.sources=sources.rows; article.attachments=attachments.rows; return article;
}
async function saveArticle(id, payload) {
  const existing=id?(await query('SELECT is_library_home FROM articles WHERE id=$1',[id])).rows[0]:null,isLibraryHome=Boolean(existing?.is_library_home);
  const fields={title:textValue(payload.title,300),title_color:/^#[0-9a-f]{6}$/i.test(payload.title_color||'')?payload.title_color:'#253229',summary:textValue(payload.summary,2000),content:cleanContent(payload.content),is_theme_home:!isLibraryHome&&(payload.is_theme_home===true||payload.is_theme_home==='on'),written_date:textValue(payload.written_date,30)||null,language:textValue(payload.language,20)||'pt-BR',theme_id:isLibraryHome?null:Number(payload.theme_id)};
  if(!fields.title) throw new Error('O título é obrigatório.'); let theme=null;if(!isLibraryHome){if(!Number.isInteger(fields.theme_id)) throw new Error('Escolha um tema para o artigo.');theme=(await query('SELECT parent_id FROM themes WHERE id=$1',[fields.theme_id])).rows[0];if(!theme)throw new Error('Escolha um tema para o artigo.');if(fields.is_theme_home&&theme.parent_id!==null)throw new Error('O artigo de apresentação deve pertencer a um tema principal.');}
  const client=await pool.connect(); try { await client.query('BEGIN'); let articleId=id;
    if(fields.is_theme_home) await client.query('UPDATE articles SET is_theme_home=0 WHERE theme_id=$1 AND id<>$2',[fields.theme_id,id||0]);
    if(id){const r=await client.query("UPDATE articles SET title=$1,title_color=$2,summary=$3,content=$4,content_format='html',is_theme_home=$5,written_date=$6,language=$7,theme_id=$8,updated_at=now() WHERE id=$9",[fields.title,fields.title_color,fields.summary,fields.content,Number(fields.is_theme_home),fields.written_date,fields.language,fields.theme_id,id]);if(!r.rowCount)throw new Error('Artigo não encontrado.');}
    else articleId=(await client.query("INSERT INTO articles(title,title_color,summary,content,content_format,is_theme_home,written_date,language,theme_id) VALUES($1,$2,$3,$4,'html',$5,$6,$7,$8) RETURNING id",[fields.title,fields.title_color,fields.summary,fields.content,Number(fields.is_theme_home),fields.written_date,fields.language,fields.theme_id])).rows[0].id;
    await Promise.all(['article_authors','article_tags','article_sources'].map(table=>client.query(`DELETE FROM ${table} WHERE article_id=$1`,[articleId])));
    for(const name of list(payload.authors)){const r=await client.query('INSERT INTO authors(name) VALUES($1) ON CONFLICT(name) DO UPDATE SET name=EXCLUDED.name RETURNING id',[name]);await client.query('INSERT INTO article_authors(article_id,author_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[articleId,r.rows[0].id]);}
    for(const name of list(payload.tags)){const r=await client.query('INSERT INTO tags(name) VALUES($1) ON CONFLICT(name) DO UPDATE SET name=EXCLUDED.name RETURNING id',[name]);await client.query('INSERT INTO article_tags(article_id,tag_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[articleId,r.rows[0].id]);}
    for(const source of Array.isArray(payload.sources)?payload.sources:[]){if(!textValue(source.title,300))continue;const r=await client.query('INSERT INTO sources(title,url,publisher,source_date) VALUES($1,$2,$3,$4) RETURNING id',[textValue(source.title,300),textValue(source.url,2000),textValue(source.publisher,300),textValue(source.source_date,30)]);await client.query('INSERT INTO article_sources(article_id,source_id) VALUES($1,$2)',[articleId,r.rows[0].id]);}
    await client.query('COMMIT');return articleId;
  }catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
}
function json(res,status,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(body));}
function body(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>250*1024*1024)reject(new Error('Arquivo muito grande (máximo de 180 MB).'));});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{});}catch{reject(new Error('JSON inválido.'));}});req.on('error',reject);});}
function staticFile(res,pathname){const file=pathname==='/'?'index.html':pathname.slice(1);const target=path.resolve(ROOT,'public',file);if(!target.startsWith(path.resolve(ROOT,'public')+path.sep)||!fs.existsSync(target))return false;const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.webmanifest':'application/manifest+json'};res.writeHead(200,{'content-type':types[path.extname(target)]||'application/octet-stream'});fs.createReadStream(target).pipe(res);return true;}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{
  res.setHeader('x-content-type-options','nosniff');res.setHeader('x-frame-options','DENY');res.setHeader('referrer-policy','no-referrer');res.setHeader('permissions-policy','camera=(), microphone=(), geolocation=()');res.setHeader('content-security-policy',"default-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self'; media-src 'self' blob:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'");
  if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.headers.origin){const expected=`${process.env.PUBLIC_HTTPS==='true'?'https':'http'}://${req.headers.host}`;if(req.headers.origin!==expected)return json(res,403,{error:'Origem da solicitação não permitida.'});}
  if(req.method==='GET'&&url.pathname==='/api/auth/status'){const user=await userFor(req);return json(res,200,{authenticated:Boolean(user),configured:(await query('SELECT 1 FROM users LIMIT 1')).rowCount>0,user});}
  if(req.method==='POST'&&url.pathname==='/api/auth/setup'){if((await query('SELECT 1 FROM users LIMIT 1')).rowCount)return json(res,409,{error:'A conta inicial já foi configurada.'});const p=await body(req),username=textValue(p.username,60),password=String(p.password||'');if(username.length<3||password.length<12)return json(res,400,{error:'Use usuário com ao menos 3 caracteres e senha com ao menos 12.'});const r=await query('INSERT INTO users(username,password_hash) VALUES($1,$2) RETURNING id',[username,hashPassword(password)]);await createSession(res,r.rows[0].id);return json(res,201,{username});}
  if(req.method==='POST'&&url.pathname==='/api/auth/login'){const p=await body(req),username=textValue(p.username,60),key=`${req.socket.remoteAddress||'local'}:${username.toLowerCase()}`;if(loginLimiter.blocked(key)){res.setHeader('retry-after','900');return json(res,429,{error:'Muitas tentativas. Aguarde alguns minutos e tente novamente.'});}const u=(await query('SELECT * FROM users WHERE lower(username)=lower($1)',[username])).rows[0];if(!u||!validPassword(p.password,u.password_hash)){loginLimiter.fail(key);return json(res,401,{error:'Usuário ou senha inválidos.'});}loginLimiter.clear(key);await createSession(res,u.id);return json(res,200,{username:u.username});}
  if(req.method==='POST'&&url.pathname==='/api/auth/logout'){const id=cookies(req).biblio_session;if(id)await query('DELETE FROM sessions WHERE id=$1',[id]);res.setHeader('set-cookie','biblio_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,204,{});}
  if(req.method==='GET'&&url.pathname==='/api/appearance'){const row=(await query("SELECT value FROM settings WHERE key='visual_theme'")).rows[0];return json(res,200,{visual_theme:row?.value||'classic'});}
  if(req.method==='PUT'&&url.pathname==='/api/auth/account'){const user=await userFor(req);if(!user)return json(res,401,{error:'Autenticação necessária.'});const p=await body(req),currentPassword=String(p.current_password||''),username=textValue(p.username,60),newPassword=String(p.new_password||''),confirmPassword=String(p.confirm_password||'');const stored=(await query('SELECT password_hash FROM users WHERE id=$1',[user.id])).rows[0];if(!stored||!validPassword(currentPassword,stored.password_hash))return json(res,400,{error:'A senha atual está incorreta.'});if(username.length<3)return json(res,400,{error:'Use usuário com ao menos 3 caracteres.'});if((await query('SELECT 1 FROM users WHERE lower(username)=lower($1) AND id<>$2',[username,user.id])).rowCount)return json(res,409,{error:'Este usuário já está em uso.'});if(newPassword&&(newPassword.length<12||newPassword!==confirmPassword))return json(res,400,{error:newPassword.length<12?'A nova senha deve ter ao menos 12 caracteres.':'A confirmação da nova senha não confere.'});const passwordHash=newPassword?hashPassword(newPassword):stored.password_hash;await query('UPDATE users SET username=$1,password_hash=$2 WHERE id=$3',[username,passwordHash,user.id]);const sessionId=cookies(req).biblio_session;await query('DELETE FROM sessions WHERE user_id=$1 AND id<>$2',[user.id,sessionId||'']);return json(res,200,{username});}
  if((url.pathname.startsWith('/api/')||url.pathname.startsWith('/media/'))&&url.pathname!=='/api/health'&&!(await userFor(req)))return json(res,401,{error:'Autenticação necessária.'});
  if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,database:'sqlite'});
  if(req.method==='GET'&&url.pathname==='/api/diagnostics'){const media=await mediaDiagnostics(query,MEDIA_DIR),integrity=pool.integrityCheck(),bible=(await bibleQuery("SELECT (SELECT count(*) FROM bible_books) books,(SELECT count(*) FROM bible_verses) verses")).rows[0];return json(res,200,{ok:integrity.length===1&&integrity[0]==='ok'&&!media.missing.length&&bible.books===66&&bible.verses>30000,database:integrity,media,bible});}
  if(req.method==='GET'&&url.pathname==='/api/home'){const row=(await query('SELECT id FROM articles WHERE is_library_home=1 LIMIT 1')).rows[0];return row?json(res,200,await details(row.id)):json(res,404,{error:'Página inicial não encontrada.'});}
  if(req.method==='GET'&&url.pathname==='/api/bible'){const translation=(await bibleQuery("SELECT * FROM bible_translations WHERE code='BLIVRE' LIMIT 1")).rows[0];if(!translation)return json(res,404,{error:'Bíblia offline não instalada.'});const books=(await bibleQuery('SELECT b.id,b.code,b.name,b.testament,b.canonical_order,max(v.chapter) chapter_count FROM bible_books b JOIN bible_verses v ON v.book_id=b.id WHERE b.translation_id=$1 GROUP BY b.id ORDER BY b.canonical_order',[translation.id])).rows;return json(res,200,{translation,books});}
  const bibleChapter=url.pathname.match(/^\/api\/bible\/books\/([A-Z0-9]{3})\/chapters\/(\d+)$/);if(req.method==='GET'&&bibleChapter){const code=bibleChapter[1],chapter=Number(bibleChapter[2]),book=(await bibleQuery("SELECT b.*,t.name translation_name,t.license,t.source_url,t.source_version FROM bible_books b JOIN bible_translations t ON t.id=b.translation_id WHERE t.code='BLIVRE' AND b.code=$1",[code])).rows[0];if(!book)return json(res,404,{error:'Livro bíblico não encontrado.'});const verses=(await bibleQuery('SELECT verse,text FROM bible_verses WHERE book_id=$1 AND chapter=$2 ORDER BY verse_order,id',[book.id,chapter])).rows;if(!verses.length)return json(res,404,{error:'Capítulo bíblico não encontrado.'});return json(res,200,{book:{code:book.code,name:book.name,testament:book.testament,canonical_order:book.canonical_order},chapter,verses,translation:{name:book.translation_name,license:book.license,source_url:book.source_url,source_version:book.source_version}});}
  if(req.method==='GET'&&url.pathname==='/api/bible/search'){const term=textValue(url.searchParams.get('q'),120),expression=bibleSearchExpression(term);if(term.length<2||!expression)return json(res,400,{error:'Digite pelo menos duas letras para pesquisar na Bíblia.'});const rows=(await bibleQuery(`SELECT b.code,b.name book_name,b.testament,v.chapter,v.verse,v.text FROM bible_verses_fts f JOIN bible_verses v ON v.id=f.rowid JOIN bible_books b ON b.id=v.book_id WHERE bible_verses_fts MATCH $1 ORDER BY rank,b.canonical_order,v.chapter,v.verse_order LIMIT 100`,[expression])).rows;return json(res,200,{query:term,results:rows});}
  if(req.method==='GET'&&url.pathname==='/api/settings'){const rows=(await query('SELECT key,value FROM settings')).rows;return json(res,200,Object.fromEntries(rows.map(item=>[item.key,item.value])));}
  if(req.method==='PUT'&&url.pathname==='/api/settings'){const p=await body(req),allowed={banner_title:120,banner_subtitle:180,banner_image:7*1024*1024,welcome_image:7*1024*1024,visual_theme:24};for(const [key,max] of Object.entries(allowed)){if(!(key in p))continue;const value=String(p[key]||'').slice(0,max);if(key.endsWith('_image')&&value&&!/^data:image\/(jpeg|png|gif|webp);base64,[a-zA-Z0-9+/=]+$/.test(value))return json(res,400,{error:'Escolha uma imagem JPEG, PNG, GIF ou WebP.'});if(key==='visual_theme'&&!/^(classic|ocean|sepia|rose|lavender|slate)$/.test(value))return json(res,400,{error:'Tema visual inválido.'});await query('INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[key,value]);}return json(res,200,{ok:true});}
  if(req.method==='GET'&&url.pathname==='/api/backup'){pool.checkpoint();const archive=path.join(os.tmpdir(),`biblio-download-${crypto.randomUUID()}.zip`);await createBackupFile(DATA_DIR,archive);const stat=fs.statSync(archive);res.writeHead(200,{'content-type':'application/zip','content-disposition':`attachment; filename="${backupName()}"`,'content-length':stat.size,'cache-control':'no-store'});const stream=fs.createReadStream(archive);stream.on('close',()=>fs.rm(archive,{force:true},()=>{}));stream.on('error',error=>{fs.rm(archive,{force:true},()=>{});res.destroy(error);});return stream.pipe(res);}
  if(req.method==='POST'&&url.pathname==='/api/restore'){if(/^application\/(?:zip|x-zip-compressed)(?:;|$)/i.test(req.headers['content-type']||'')){await receiveFile(req,RESTORE_FILE,180*1024*1024);}else{const payload=await body(req),match=String(payload.dataUrl||'').match(/^data:application\/(zip|x-zip-compressed);base64,(.+)$/);if(!match)return json(res,400,{error:'Selecione um arquivo ZIP de backup da Biblio.'});const archive=Buffer.from(match[2],'base64');if(archive.length>180*1024*1024)return json(res,400,{error:'Arquivo muito grande (máximo de 180 MB).'});fs.writeFileSync(RESTORE_FILE,archive,{flag:'wx',mode:0o600});}try{const check=new (require('adm-zip'))(RESTORE_FILE);if(!check.getEntry('manifest.json')||!check.getEntry('data/biblio.db'))throw new Error('Esta não é uma cópia válida da Biblio.');}catch(error){fs.rmSync(RESTORE_FILE,{force:true});throw error;}json(res,202,{ok:true});return setTimeout(()=>process.exit(75),150);}
  if(url.pathname.startsWith('/media/')){const storage=path.basename(decoded(url.pathname));const attachment=(await query('SELECT mime_type FROM attachments WHERE storage_name=$1',[storage])).rows[0];const file=path.join(MEDIA_DIR,storage);if(!attachment||!fs.existsSync(file))return json(res,404,{error:'Arquivo não encontrado.'});res.writeHead(200,{'content-type':attachment.mime_type,'content-disposition':'inline','x-content-type-options':'nosniff'});return fs.createReadStream(file).pipe(res);}
  if(req.method==='GET'&&url.pathname==='/api/themes')return json(res,200,(await query('SELECT t.id,t.name,t.parent_id,t.created_at,count(a.id)::int article_count,(SELECT h.id FROM articles h WHERE h.theme_id=t.id AND h.is_theme_home=1 LIMIT 1) home_article_id FROM themes t LEFT JOIN articles a ON a.theme_id=t.id GROUP BY t.id ORDER BY CASE WHEN t.parent_id IS NULL THEN 0 ELSE 1 END,t.name')).rows);
  if(req.method==='POST'&&url.pathname==='/api/themes'){const p=await body(req),name=textValue(p.name,80),parentId=p.parent_id===undefined||p.parent_id===null||p.parent_id===''?null:Number(p.parent_id);if(name.length<2)return json(res,400,{error:'Informe um tema com pelo menos 2 caracteres.'});if(parentId!==null){if(!Number.isInteger(parentId)||parentId<1)return json(res,400,{error:'Escolha um tema principal válido.'});const parent=(await query('SELECT parent_id FROM themes WHERE id=$1',[parentId])).rows[0];if(!parent)return json(res,404,{error:'Tema principal não encontrado.'});if(parent.parent_id!==null)return json(res,400,{error:'Subtemas só podem pertencer a um tema principal.'});}const r=await query('INSERT INTO themes(name,parent_id) VALUES($1,$2) RETURNING id,name,parent_id,created_at',[name,parentId]);return json(res,201,{...r.rows[0],article_count:0});}
  if(req.method==='GET'&&url.pathname==='/api/articles'){const q=textValue(url.searchParams.get('q'),200),theme=Number(url.searchParams.get('theme'));let sql='SELECT id FROM articles WHERE is_library_home=0',args=[],order='updated_at DESC';if(q){args.push('%'+q+'%');sql+=' AND (title ILIKE $1 OR summary ILIKE $1 OR content ILIKE $1)';}else if(Number.isInteger(theme)&&theme>0){args.push(theme,theme);sql+=' AND (theme_id=$1 OR theme_id IN (SELECT id FROM themes WHERE parent_id=$2))';order='is_theme_home DESC, updated_at DESC';}sql+=' ORDER BY '+order+' LIMIT 100';const ids=(await query(sql,args)).rows.map(x=>x.id);return json(res,200,await Promise.all(ids.map(details)));}
  const match=url.pathname.match(/^\/api\/articles\/(\d+)$/);if(req.method==='GET'&&match){const a=await details(Number(match[1]));return a?json(res,200,a):json(res,404,{error:'Artigo não encontrado.'});}if(req.method==='POST'&&url.pathname==='/api/articles')return json(res,201,await details(await saveArticle(null,await body(req))));if(req.method==='PUT'&&match)return json(res,200,await details(await saveArticle(Number(match[1]),await body(req))));if(req.method==='DELETE'&&match){const articleId=Number(match[1]);if((await query('SELECT is_library_home FROM articles WHERE id=$1',[articleId])).rows[0]?.is_library_home)return json(res,400,{error:'A página inicial não pode ser excluída.'});const files=(await query('SELECT storage_name FROM attachments WHERE article_id=$1',[articleId])).rows;await query('DELETE FROM articles WHERE id=$1',[articleId]);for(const item of files){try{fs.rmSync(path.join(MEDIA_DIR,item.storage_name),{force:true});}catch(error){console.error(`Mídia órfã após exclusão: ${item.storage_name}: ${error.message}`);}}return json(res,204,{});}
  const upload=url.pathname.match(/^\/api\/articles\/(\d+)\/attachments$/);if(req.method==='POST'&&upload){const articleId=Number(upload[1]);if(!(await query('SELECT 1 FROM articles WHERE id=$1',[articleId])).rowCount)return json(res,404,{error:'Artigo não encontrado.'});let name,mimeType,size,temporary;if(req.headers['content-type']==='application/octet-stream'){name=path.basename(decoded(req.headers['x-file-name']||'arquivo'));mimeType=String(req.headers['x-mime-type']||'');temporary=path.join(MEDIA_DIR,`.upload-${crypto.randomUUID()}`);size=await receiveFile(req,temporary,25*1024*1024);}else{const p=await body(req),raw=String(p.dataUrl||''),parts=raw.match(/^data:([^;]+);base64,(.+)$/);if(!parts)return json(res,400,{error:'Envie uma imagem ou vídeo compatível.'});name=path.basename(String(p.name||'arquivo'));mimeType=parts[1];const buffer=Buffer.from(parts[2],'base64');size=buffer.length;if(size>25*1024*1024)return json(res,400,{error:'Arquivo muito grande (máximo de 25 MB).'});temporary=path.join(MEDIA_DIR,`.upload-${crypto.randomUUID()}`);fs.writeFileSync(temporary,buffer,{flag:'wx',mode:0o600});}if(!/^image\/(jpeg|png|gif|webp)$|^video\/(mp4|webm|quicktime)$/.test(mimeType)){fs.rmSync(temporary,{force:true});return json(res,400,{error:'Envie uma imagem ou vídeo compatível.'});}const signature=Buffer.alloc(16),descriptor=fs.openSync(temporary,'r');const read=fs.readSync(descriptor,signature,0,signature.length,0);fs.closeSync(descriptor);if(!validMediaSignature(mimeType,signature.subarray(0,read))){fs.rmSync(temporary,{force:true});return json(res,400,{error:'O conteúdo do arquivo não corresponde ao formato informado.'});}const storage=`${crypto.randomUUID()}-${name.replace(/[^a-zA-Z0-9._-]/g,'_')}`,file=path.join(MEDIA_DIR,storage);fs.renameSync(temporary,file);try{const r=await query('INSERT INTO attachments(article_id,original_name,storage_name,mime_type,size_bytes) VALUES($1,$2,$3,$4,$5) RETURNING *',[articleId,name,storage,mimeType,size]);return json(res,201,r.rows[0]);}catch(error){fs.rmSync(file,{force:true});throw error;}}
  const attachmentMatch=url.pathname.match(/^\/api\/attachments\/(\d+)$/);if(req.method==='DELETE'&&attachmentMatch){const item=(await query('SELECT * FROM attachments WHERE id=$1',[Number(attachmentMatch[1])])).rows[0];if(!item)return json(res,404,{error:'Anexo não encontrado.'});const article=(await query('SELECT content,content_format FROM articles WHERE id=$1',[item.article_id])).rows[0];await query('BEGIN');try{await query('DELETE FROM attachments WHERE id=$1',[item.id]);await query('UPDATE articles SET content=$1,updated_at=now() WHERE id=$2',[article?.content_format==='html'?cleanContent(article.content,item.storage_name):(article?.content||''),item.article_id]);await query('COMMIT');}catch(error){await query('ROLLBACK');throw error;}try{fs.rmSync(path.join(MEDIA_DIR,item.storage_name),{force:true});}catch(error){console.error(`Mídia órfã após exclusão: ${item.storage_name}: ${error.message}`);}return json(res,204,{});}
  if(staticFile(res,url.pathname))return;json(res,404,{error:'Rota não encontrada.'});
}catch(error){json(res,400,{error:error.message||'Erro inesperado.'});}});
init().then(()=>{const cleanup=setInterval(()=>query('DELETE FROM sessions WHERE expires_at < now()').catch(error=>console.error(error)),60*60*1000);cleanup.unref();server.listen(PORT,'127.0.0.1',()=>console.log(`Biblio disponível em http://127.0.0.1:${PORT} (SQLite local)`));}).catch(error=>{console.error(error);process.exit(1);});
function shutdown(){server.close(()=>{biblePool.close();pool.close();process.exit(0);});setTimeout(()=>process.exit(1),5000).unref();}
process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
